---
description: A game of gravity
title: Gravity
requires:
  - jquery
  - underscore
  - underscore.string
  - backbone
  - bootstrap
  - paper
  - physics  

args:
  - nplanets
  - elements

missions:
  - title: Sandbox
    rule: nplanets > 0
    enabled: true
    text: Just play around!
    help:      
      - on: start
        message: |
          # @icon-rocket Sandbox 
          @separator
          Your very first mission: just add one planet and make it orbit around the star!
          Click "Next" to learn how.
          @proceed
        
      - on: proceed
        message: |
          First, @icon-tap tap anywhere to add a new planet. 
           
      - on: change:nplanets
        message: >
          That's your first planet! Now try to @icon-drag *drag* the planet
          to change its position.

      - on: planet:drag
        message: >
          Awesome! Now  @icon-drag *drag* the tip of the arrow to change the speed
          and direction of the planet.

      - on: planet:dragvelocity
        message: |
          Now *tap on the @icon-star star* to let the planet orbit;
          tap on the @icon-star star again to pause.

          
          (You can also tap on the @icon-menu menu
          button to see more options.)

      - on: win
        message: >
           @h1 @icon-win Mission accomplished! @/h1
           @separator
           Whoohoo! Look at that planet go! When you're ready, proceed to the next mission.
           @proceed-win
                  
  - title: Circular orbit
    rule: nplanets > 0 && elements.eccentricity[0] < 0.1 && elements.eccentricity[0] > -0.001
    enabled: true
    text: Get a circular orbit.
    help:
      - message: >
            @h1 @icon-rocket Circular orbit @/h1
            @separator
            Now, let's try to place a planet in a circular orbit. First, add a new planet.
            
      - on: change:nplanets
        message: >-
          The eccentricity of the planet is @eccentricity. This is where it ends! The rest is
          not done yet :(
            
  - title: Eccentric orbit
    rule: ecc[0] > 0.02
    enabled: true
    text: >
      Get an eccentric orbit.
  
  - title: Hyperbolic orbit
    rule: ecc[0] > 1
    enabled: true
    text: >
      Get a hyperbolic orbit.