---
description: A game of gravity
title: Orbits
requires:
  - device
  - color
  - jquery
  - underscore
  - underscore.string
  - backbone
  - bootstrap
  - paper
  - physics
  - constants
  - utils
  - animalese
  - textillate
  
args:
  - nplanets
  - elements
  - collided

assets:
  music:
    level: sounds/level_v2_low.mp3
    groove: sounds/groove-loop1_v2-low.mp3
    triumph: sounds/triumph_v4_low.mp3
    sad: sounds/sad_v2_low.mp3
  effects:
    lose: sounds/lose.mp3
    win: sounds/win.mp3
    collision: sounds/collision.mp3
    proceed: sounds/proceed.wav
    clickety: sounds/proceed.wav
    addPlanet: sounds/add-planet.mp3
    "planet:drag": sounds/drag.mp3
  
starsBounty: 24
missions:
  - title: Practice Mode
    subtitle: Create your first planet.
    win: Woohoo! Look at that planet go!
    lose: Darn! You forgot to add the planet!
    rule: nplanets > 0
    music: level
    enabled: true
    icon: icon-practice
    constraints:
      nplanets: 1
    help:      
      - on: start
        message: |          
          @fly @noninteractive @groknar
          "I quit!" Groknar, Lead Engineer of Nova Planetia and head of planetary development, 
          threw the digipad on the Big Boss' desk.
          @proceed
      
      - on: proceed
        message: |          
          @fly @noninteractive @boss
          "But we just got a huge contract to develop 
          the Arcturus Nebular Cloud!" Big Boss Reaz-7 protested.

          
          "We already brought 1000 
          planets out of the Eridani drydocks and they're waiting to be deployed!"
          @proceed

      - on: proceed
        message: |
          @fly @noninteractive @groknar
          Groknar spat.  "Maybe next time you'll get us a breakroom espresso maker."  He slammed the door.
          @proceed
          
      - on: proceed
        message: |
          @fly @noninteractive @boss
          Reaz-7 turned furiously.  "@name!  You're hired.  Get in the spacedozer and start training!"
          @proceed

      - on: proceed
        message: |
          @noninteractive @stop-fly
          *@name*, it's your very first training mission: just add one planet and make it orbit around the star!


          *Click "Next" to learn how.*
          @proceed

      - on: proceed
        message: |
          @noninteractive
          Your goal is to complete your mission in as little time as possible. As time passes, the number
          of stars you can earn will decrease.
          @proceed
      
      - on: proceed
        message: |
          @noninteractive
          To review your current mission at any time, click on the @icon-help Help button!
          
          *Now, let's start playing!*
          @proceed
          
      - on: proceed
        message: >
          First, *@icon-tap tap anywhere* to add a new planet. 
           
      - on: change:nplanets
        message: >
          That's your first planet! Now try to *@icon-drag drag the planet*
          to change its position.

      - on: planet:drag
        message: |
          Awesome!  Lots of useful information about your planet is shown in the upper right, 
          such as its distance from the star, its speed, and the time it takes to orbit the star.  
          @proceed
          
      - on: proceed
        message: >
          Try it out!  @icon-drag *Drag the head of the arrow* to change the speed
          and direction of the planet, and see its speed change in the upper right. 

      - on: planet:dragvelocity
        message: |          
          As you change the position and speed of the planet, its orbital path will change.

          
          Now *tap on the @icon-star star* to let the planet orbit!
          
      - on: win
        message: |
          @boss
          Big Boss Reaz-7 says, "Good work, but we need you to train quickly!  We need to 
          engineer all of the new star systems forming in the Arcturus Nebula, and our 
          customers are very... picky."

      - on: lose
        message: |
          @boss
          Good job, rookie... not! 
          
                  
  - title: Crash & Burn
    rule: nplanets > 0 && collided
    enabled: true
    subtitle: Make your planet collide with the star.
    win: Those were impressive fireworks!
    lose: You avoided crashing into the star.
    icon: icon-crash
    music: groove
    constraints:
      nplanets: 1
    help:
      - on: start
        message: |   
           @boss
           The ironic Asteroid Metal band *Suddenly Starburst* wants to play their farewell concert on a new planet... as it crashes into its Sun.
           @close
           
      - on: hint
        message: |
           @boss
           Try launching the planet towards the star, rookie.
           @hide-5
           
      - on: win
        message: |
          @boss
          Big Boss Reaz-7 says, "Good work, but we need you to train quickly!  We need to 
          engineer all of the new star systems forming in the Arcturus Nebula, and our 
          customers are very... picky."
      

  - title: Ejected!
    rule: nplanets > 0 && elements[0].eccentricity > 1
    enabled: true
    subtitle: Add a planet that escapes the pull of its star.
    win: Bye bye planet!
    lose: Oh no!  You're caught by the pull of gravity!
    icon: icon-hyperbolic
    constraints:
      nplanets: 1

  - title: Elliptical Orbit
    rule: nplanets > 0 && elements[0].eccentricity > 0.2 && elements[0].eccentricity < 0.99 && !collided
    enabled: true
    subtitle: Add a planet in an elliptical (oval) orbit.
    win: So elliptical!
    lose: That orbit could be more elliptical...
    icon: icon-elliptical
    constraints:
      nplanets: 1
    help:
      - on: win
        message: |
          {img/boss_angry.png width=150 class=avatar-right} @enter-avatar
          Did you know that you can view your creation in all its glory?


          @icon-drag Drag to
          rotate the view!     

  - title: Circular Orbit
    rule: nplanets > 0 && elements[0].eccentricity < 0.15 && elements[0].eccentricity > -0.001
    enabled: true
    subtitle: Add a planet in a circular orbit.
    win: Sweet! That's... pretty circular!
    lose: That orbit is not very circular.
    icon: icon-circular
    constraints:
      nplanets: 1

  - title: Speed vs. distance (40 km/s)
    subtitle: Add a planet in a circular orbit at 40 km/s.
    rule: nplanets > 0 && elements[0].eccentricity < 0.15 && elements[0].eccentricity > -0.001
    icon: icon-circ-rvs
    constraints:
      speed: 40
      direction: perpendicular
      nplanets: 1
    enabled: true
    help:
      - on: start
        message: |          
          A new type of mission!


          In this mission, your planet will have a *fixed speed (40 km/s)*
          and a *fixed direction* (perpendicular to the line connecting the star and the planet).
          @proceed
      - on: proceed
        message: |
          To win this mission, you will have to place the planet at just the right distance to get
          a circular orbit. 
    win: So circular!
    lose: The orbit was not quite circular... Try moving the planet to a different distance.

  - title: Speed vs. distance (30 km/s)
    subtitle: Add a planet in a circular orbit at 30 km/s.
    rule: nplanets > 0 && elements[0].eccentricity < 0.15 && elements[0].eccentricity > -0.001
    icon: icon-circ-rvs    
    constraints:
      speed: 30
      direction: perpendicular
      nplanets: 1
    enabled: true
    win: So circular!
    lose: The orbit was not quite circular... Try moving the planet to a different distance.    
    
  - title: Speed vs. distance (25 km/s)
    subtitle: Add a planet in a circular orbit at 25 km/s.
    rule: nplanets > 0 && elements[0].eccentricity < 0.15 && elements[0].eccentricity > -0.001
    icon: icon-circ-rvs    
    constraints:
      speed: 25
      direction: perpendicular
      nplanets: 1
    enabled: true
    win: So circular!
    lose: The orbit was not quite circular... Try moving the planet to a different distance.

  - title: Multi-planet test
    subtitle: Work dammit!
    rule: nplanets > 0 
    icon: icon-circ-rvs
    enabled: true
    win: So circular!
    lose: The orbit was not quite circular... Try moving the planet to a different distance.
    constraints:
      nplanets: 2

  - title: Barycentric gravity
    subtitle: Work dammit!
    rule: nplanets > 0 
    icon: icon-circ-rvs
    enabled: true
    win: So circular!
    lose: The orbit was not quite circular... Try moving the planet to a different distance.
    bodies:
      - mass: 0.25
        x: 1
        y: 0
        z: 0
        u: 0
        v: 0.017
        z: 0
