---
description: A game of gravity
title: Gravity
requires:
  - jquery
  - underscore
  - backbone
  - bootstrap
  - paper
  - physics  

      
  
missions:
  - title: Sandbox
    rule: nplanets >= 0 && ecc[0] < 1
    enabled: true
    text: >-
      Your first mission: just add one planet and make it orbit around the star!
      <div class="separator"></div>
      <span class="icon-tap"></span> Tap anywhere to add a planet, then <span class="icon-drag"></span>
      drag the planet and its velocity vector. <br>
      <span class="icon-star"></span> Tap on the star to let the planet orbit.
      
  - title: Circular orbit
    rule: ecc[0] < 0.02
    enabled: true
    text: >-
      Get a circular orbit.

  - title: Eccentric orbit
    rule: ecc[0] > 0.02
    enabled: true
    text: >-
      Get an eccentric orbit.

  - title: Hyperbolic orbit
    rule: ecc[0] > 1
    enabled: true
    text: >-
      Get a hyperbolic orbit.