---
description: A game of gravity
title: Orbits
requires:
  - device
  - color
  - jquery
  - underscore
  - underscore.string
  - jsplumb
  - uikit
  - backbone
  - paper
  - physics
  - constants
  - utils
  
args:
  - nplanets
  - elements
  - collided
  
formulas:
  - rule
  - starsrule

avatars:
  @groknar: {img/groknar.gif width=150 class=avatar-left} @enter-avatar
  @boss: {img/boss.gif width=150 class=avatar-right} @enter-avatar
  @praetor: {img/praetor.png width=130 class=avatar-left} @enter-avatar
  
assets:
  music:
    level: sounds/level_v3_quietpiano.mp3
    groove: sounds/groove-loop1_v2-low.mp3
    triumph: sounds/triumph_v4_low.mp3
    sad: sounds/sad_v2_low.mp3
    standard: sounds/standard.mp3
    darktriumph: sounds/darktriump_v2.mp3
    creep: creep_v2.mp3
    bloop: bloop-dungeon_v3.mp3
    lurk: lurk_v3.mp3
  effects:
    lose: sounds/lose.mp3
    win: sounds/win.mp3
    collision: sounds/collision.mp3
    proceed: sounds/proceed.wav
    clickety: sounds/proceed.wav
    addPlanet: sounds/add-planet.mp3
    "planet:drag": sounds/drag.mp3
  
missions:
  - title: Practice Mode
    name: practice
    subtitle: Create your first planet.
    win: Woohoo! Look at that planet go!
    lose: Darn! You forgot to add the planet!
    rule: nplanets > 0 
    music: level
    enabled: true
    icon: icon-practice
    starsrule: 3
    color: cyan
    intro: |
      Big Boss Reaz-7 pushes aside the giant potted plant on his gold leaf desk and glares at you.


      *"You! Who are you? Don't just stand at the door, press that Play button!"*
      
    constraints:
      nplanets: 1
    help:      
      - on: start
        message: |          
          @fly @noninteractive @groknar
          "I quit!" Groknar, Lead Engineer of Nova Planetia and head of planetary development, 
          threw the digipad on the Big Boss' desk.
          @proceed
      
      - on: proceed
        message: |          
          @fly @noninteractive @boss
          "But we just got a huge contract to develop 
          the Arcturus Nebular Cloud!" Big Boss Reaz-7 protested.

          
          "We already brought 1000 
          planets out of the Eridani drydocks and they're waiting to be deployed!"
          @proceed

      - on: proceed
        message: |
          @fly @noninteractive @groknar
          Groknar spat.  "Maybe next time you'll get us a breakroom espresso maker."  He slammed the door.
          @proceed
          
      - on: proceed
        message: |
          @fly @noninteractive @boss
          Reaz-7 turned furiously.  "@name!  You're hired.  Get in the spacedozer and start training!"
          @proceed

      - on: proceed
        message: |
          @fly @noninteractive @boss
          You’ll be paid in “stars"!  Stars can be redeemed at the company store for special prizes later on.
          Your payment is based on how well you do the job at hand.
          @proceed
          
      - on: proceed
        message: |
          @noninteractive @stop-fly @boss
          But first, you need to get through our specially mandated training program.  It’s simple enough: make a planet and have it orbit around the star!          
          @proceed
      
      - on: proceed
        message: |
          @noninteractive @boss
          To review your current mission at any time, click on the @icon-help Help button!

          
          *Now, let's start training!*
          @proceed
          
      - on: proceed
        message: >
          @boss @disable-star  @disable-planet-drag @disable-velocity @disable-force
          First, *@icon-tap tap anywhere* to add a new planet. 
           
      - on: change:nplanets
        message: >
          @boss @disable-star @disable-velocity @disable-force @refresh
          That's your first planet! Now try to *@icon-drag drag the planet*
          to change its position.

      - on: planet:drag
        message: |
          @boss @disable-star @disable-velocity @disable-force @refresh
          Great job, rookie! Lots of useful information about your planet is shown in the upper right, 
          such as its distance from the star and its speed.
          @proceed

      - on: proceed
        message: |
          @boss @disable-star @disable-planet-drag @disable-velocity
          *Check out that yellow arrow!*


          As you move the planet closer and further away from the star, the gravitational force of
          the star on the planet gets stronger and weaker.
          @proceed-hidden
          
        script: |
          var t = 0;
          var min_d = 0.4;
          var max_d = 1.1;
          var step = 0.005;
          window.ORIGINAL_X = app.positionForBody(0);
          var direction = 1;
          _.defer(function() {
          
          app.animateUntil("proceed", function() {
          t += direction * step;
          var d = (max_d - min_d) * t * t + min_d;
          if (d < min_d || d > max_d) direction *= -1;
          
          app.setPositionForBody(0, [ d, -d, 0 ]);
          draw.showForces(0);
          }, function() { draw.hideForces(); app.setPositionForBody(0, window.ORIGINAL_X); }, 1000);
          });
          _.delay(function() { $("#help-next").fadeIn();  }, 15000);
          
      - on: proceed
        message: >
          @disable-star @refresh
          Now try to @icon-drag *drag the head of the speed arrow* to change the speed
          and direction of the planet, and see its speed change in the upper right. 

      - on: planet:dragvelocity
        message: |          
          As you change the position and speed of the planet, its orbital path will change.

          
          Now *tap on the @icon-star star* to let the planet orbit!
          
      - on: win3
        message: |
          @boss
          Good work, but we need you to train quickly!  We need to 
          engineer all of the new star systems forming in the Arcturus Nebula, and our 
          customers are very... picky."

      - on: lose
        message: |
          @boss
          Maybe I should have bought that breakroom espresso maker instead of hiring you.
          
                  
  - title: Crash & Burn
    rule: nplanets > 0 && collided
    name: crash
    starsrule: 3
    enabled: true
    subtitle: Make your planet collide with the star.
    win: Those were impressive fireworks!
    lose: You avoided crashing into the star.
    icon: icon-crash
    music: groove
    colors: red
    intro: |
      The ironic Asteroid Metal band *Suddenly Starburst* wants to play their farewell concert on a new planet... as it crashes into its Sun.
    constraints:
      nplanets: 1
    help:           
      - on: hint
        message: |
           @boss
           Try launching the planet towards the star, rookie.
           @hide-5

      - on: lose
        message: |
          @boss
          At least they burned up ironically.  Now make sure they impact! It’s a big star out there.
          
      - on: win3
        message: |
          @boss
          They just failed to miss the star.  Good work!
      

  - title: Ejected!
    rule: nplanets > 0 && elements[0].eccentricity > 0.9 && !collided
    name: ejected
    color: orange
    starsrule: |
      (elements[0].eccentricity < 1.25 ? 3 : (elements[0].eccentricity < 1.75 ? 2 : 1))
    enabled: true
    music: sad
    subtitle: Add a planet that escapes the pull of its star.
    win: Bye bye planet!
    lose: Oh no!  You're caught by the pull of gravity!
    icon: icon-hyperbolic
    intro: |
      The Empress of the Planet Zanimech wants to set up her loud father-in-law, Praetor Berk-ork,  on a beautiful new planetary estate... on a one-way trip out of the star system.
    constraints:
      nplanets: 1
    help:
      - on: lose
        message: |
           @boss
           A little more oomph in your orbit?

      - on: win1
        message: |
          @boss
          Whoa there, nelly.  We don’t want to give the customer whiplash, slow down a little.
      
      - on: win2
        message: |
          @boss
          Can we make the ejection a little more subtle?

      - on: win3
        message: |
          @boss
          Perfect, he’ll never notice until he’s out of the system.

  - title: Elliptical Orbit
    rule: nplanets > 0 && elements[0].eccentricity > 0.01 && elements[0].eccentricity < 0.99 && !collided
    starsrule: |
      (elements[0].eccentricity < 0.4 ? 1 : (elements[0].eccentricity < 0.7 ? 2 : 3))
    enabled: true
    name: elliptical
    color: gold
    music: triumph
    subtitle: Add a planet in an elliptical (oval) orbit.
    win: So elliptical! 
    lose: That orbit could be more elliptical...
    icon: icon-elliptical
    intro: |
      The people of Selia Prime are bored with always orbiting between the same planets.  Now they want to resettle on a world that gently tours both the inner and outer solar system at different times of year. High Councilor Zeniak pulls out his cyber binoculars eagerly and awaits a fresh night sky.
    constraints:
      nplanets: 1
    help:
      - on: lose
        message: |
          @boss
          I said TOUR the solar system, not become a permanent piece of space junk!  Make it an elliptical orbit.

      - on: win1
        message: |
          @boss
          Surely you can make the orbit more XTREME than that.
      
      - on: win2
        message: |
          @boss
          I still want to see entire solar system; can you work on that?

      - on: win3
        message: |
          @boss
          I feel the rush already!

  - title: The speed of planets
    enabled: true
    value: 1
    type: single-choice
    name: elliptical_question
    subtitle: Get an extra star by answering this question.
    intro: |
      Big Boss Reaz-7 says, "The press is banging down my door with questions.  Go out there and deal with them!  Don't say anything to embarrass me or you're in trouble." 

      
      He pauses and smirks.  


      "Also, have fun with it."
    win: That's the right answer!
    lose: Not quite right.
    icon: icon-single
    question: |
      @boss @fly
      How do planets in elliptical orbits move when they are far from their star?
    choices:
      - They slow down.
      - They speed up.
      - They move at a constant speed.
    answer: 0
    help:
      - on: win
        message: |
          @boss
          That's right, @name! Puny humans call this property "[Kepler's 2nd law](http://howthingsfly.si.edu/media/kepler%E2%80%99s-second-law)".

      - on: lose
        message: |
          @boss
          You might want to practice this out a bit in the sandbox. 

  - title: Circular Orbit
    rule: nplanets > 0 && elements[0].eccentricity < 0.15 && elements[0].eccentricity > -0.001 && !collided
    enabled: true
    name: circular
    music: triumph
    subtitle: Add a planet in a circular orbit.
    win: Sweet! That's... pretty circular!
    lose: That orbit is not very circular.
    icon: icon-circular
    intro: |
      The Arkanids are really, really picky about the amount of sunlight on their planet because their chocolate pod plants are a Galaxywide delicacy.  They don't want their orbit to change at all based on the time of year.
    constraints:
      nplanets: 1


  - title: Speed vs. distance (40 km/s)
    subtitle: Add a planet in a circular orbit at 40 km/s.
    rule: nplanets > 0 && elements[0].eccentricity < 0.15 && elements[0].eccentricity > -0.001 && !collided
    icon: icon-circ-rvs
    color: blue
    music: level
    name: speed_vs_distance_40
    constraints:
      speed: 40
      direction: perpendicular
      nplanets: 1
    enabled: true
    intro: |
      A new type of mission!

      In this mission, your planet will have a *fixed speed (40 km/s)*
      and a *fixed direction* (perpendicular to the line connecting the star and the planet).

      To win this mission, you will have to place the planet at just the right distance to get
      a circular orbit. 

    win: So circular!
    lose: The orbit was not quite circular... Try moving the planet to a different distance.

  - title: Speed vs. distance (30 km/s)
    subtitle: Add a planet in a circular orbit at 30 km/s.
    rule: nplanets > 0 && elements[0].eccentricity < 0.15 && elements[0].eccentricity > -0.001 && !collided
    icon: icon-circ-rvs
    music: level    
    name: speed_vs_distance_30
    color: blue
    constraints:
      speed: 30
      direction: perpendicular
      nplanets: 1
    enabled: true
    win: So circular!
    lose: The orbit was not quite circular... Try moving the planet to a different distance.
    intro: |
      The Arkanids didn't like their first planet.  Perhaps the shadows were wrong.  Their leader DEMANDS that you make a new system with their planet moving at a very specific speed of 30 km/s.

   
  - title: Speed vs. distance (25 km/s)
    subtitle: Add a planet in a circular orbit at 25 km/s.
    rule: nplanets > 0 && elements[0].eccentricity < 0.15 && elements[0].eccentricity > -0.001 && !collided
    icon: icon-circ-rvs    
    color: blue
    name: speed_vs_distance_25
    constraints:
      speed: 25
      direction: perpendicular
      nplanets: 1
    enabled: true
    win: So circular!
    lose: The orbit was not quite circular... Try moving the planet to a different distance.
    intro: |
      Still not satisfied, the leader of the Arkanids demands a different planet moving at 25 km/s for more optimal growing conditions.

  - title: Boss level
    subtitle: Boss level test
    name: boss_arcturus
    icon: icon-boss

  - title: Multi-planet test
    subtitle: Under construction...
    rule: nplanets > 0 
    name: multi-planet-test
    icon: icon-circ-rvs
    enabled: true
    win: So circular!
    lose: The orbit was not quite circular... Try moving the planet to a different distance.
    constraints:
      nplanets: 2

  - title: Barycentric gravity
    subtitle: Under construction...
    rule: nplanets > 0 
    icon: icon-circ-rvs
    enabled: true
    name: barycentric
    win: So circular!
    lose: The orbit was not quite circular... Try moving the planet to a different distance.
    bodies:
      - mass: 0.25
        x: 1
        y: 0
        z: 0
        u: 0
        v: 0.017
        z: 0
