---
description: A game of gravity
title: Gravity
requires:
  - jquery
  - underscore
  - backbone
  - bootstrap
  - paper
  - physics
  
missions:
  - title: Sandbox
    rule: .next
    enabled: true;
    text: >-
      Try it out.
    
  - title: Circular orbit
    rule: ecc < 0.02
    enabled: true
    text: >-
      Get a circular orbit.

  - title: Eccentric orbit
    rule: ecc > 0.02
    enabled: true
    text: >-
      Get an eccentric orbit.

  - title: Hyperbolic orbit
    rule: ecc > 1
    enabled: true
    text: >-
      Get a hyperbolic orbit.