---
description: A game of gravity
title: Gravity
requires:
  - color
  - jquery
  - underscore
  - underscore.string
  - backbone
  - bootstrap
  - paper
  - physics
  - constants

args:
  - nplanets
  - elements

missions:
  - title: Practice Mode
    subtitle: Create your first planet.
    win: Woohoo! Look at that planet go!
    lose: Darn! You forgot to add the planet!
    rule: nplanets > 0
    enabled: true
    help:      
      - on: start
        message: |          
          @noninteractive
          Your very first mission: just add one planet and make it orbit around the star!


          *Click "Next" to learn how.*
          @proceed

      - on: proceed
        message: |
          @noninteractive
          Your goal is to complete your mission in as little time as possible. Your current
          elapsed time is shown in the top right corner.  Other information about your planet 
          is shown, such as its distance from the star, its speed, and the time it takes to orbit.
          @proceed
          
      - on: proceed
        message: |          
          @noninteractive
          To review your current mission at any time, click on the @icon-help Help button!
          
          *Now, let's start playing!*
          @proceed
          
      - on: proceed
        message: >          
          First, *@icon-tap tap anywhere* to add a new planet. 
           
      - on: change:nplanets
        message: >
          That's your first planet! Now try to *@icon-drag drag the planet*
          to change its position.

      - on: planet:drag
        message: >
          Awesome! Now  @icon-drag *drag the tip of the arrow* to change the speed
          and direction of the planet. 

      - on: planet:dragvelocity
        message: |          
          As you change the position and speed of the planet, its orbital path will change.

          
          Now *tap on the @icon-star star* to let the planet orbit!
          
                  
  - title: Circular orbit
    rule: nplanets > 0 && elements[0].eccentricity < 0.1 && elements[0].eccentricity > -0.001
    enabled: true
    subtitle: Add a planet in a circular orbit.
    win: Hot damn! That's... pretty circular!
    lose: That orbit is not very circular.
    icon: icon-circular

  - title: Elliptical orbit
    rule: nplanets > 0 && elements[0].eccentricity > 0.1 && elements[0].eccentricity < 0.99
    enabled: true
    subtitle: Add a planet in an eccentric orbit.
    win: So elliptical!
    lose: That orbit is not elliptical...
    icon: icon-elliptical

  - title: Ejected (hyperbolic)
    rule: nplanets > 0 && elements[0].eccentricity > 1
    enabled: true
    subtitle: Add a planet in a hyperbolic orbit.
    win: Bye bye planet!
    lose: That orbit is not quite hyperbolic.
    icon: icon-hyperbolic

  - title: Crash & burn
    rule: nplanets > 0 && elements[0].eccentricity > 1
    enabled: true
    subtitle: Make your planet collide with the star.
    win: So elliptical!
    lose: That orbit is not eccentric...
    icon: icon-crash

  - title: Speed vs. radius (circular)
    rule: nplanets > 0 && elements[0].eccentricity > 1
    enabled: true
    subtitle: TBD
    win: So elliptical!
    lose: That orbit is not eccentric...

  - title: Speed vs. radius (elliptical)
    rule: nplanets > 0 && elements[0].eccentricity > 1
    enabled: true
    subtitle: TBD
    win: So elliptical!
    lose: That orbit is not eccentric...

