---
description: Kiosk screen saver
title: Screen Saver
requires:
  - jquery
  - underscore
  - uikit
  - utils
  - transit
  - device


feeds:
#  - url: http://photojournal.jpl.nasa.gov/rss/new 
#    attrib: NASA PhotoJournal &mdash; photojournal.jpl.nasa.gov
#    base: http://photojournal.jpl.nasa.gov/jpegMod/
#    transform: photojournal
  - url: http://hubblesite.org/newscenter/newscenter_rss.php
    attrib: HubbleSite &mdash; www.hubblesite.org

  - url: http://apod.nasa.gov/apod.rss
    attrib: Astronomy Picture of the Day &mdash; apod.nasa.gov
    base: http://apod.nasa.gov/apod/


blacklisted:
  - hs-2015-07-a-thumb.jpg
  - PIA19059_modest.jpg
  - PIA19242_modest.jpg
  - PIA19244_modest.jpg
  
slides:
  - title: <strong>Tap</strong> and <strong>drag</strong> to interact with the apps.
    img: img/tap_and_drag.png
    fixed: true

  - title: Astronomers Discover Ancient Solar System with Five Earth-sized Planets
    img: img/Kepler444_Illo.jpg
    attrib: McDonald Observatory &mdash; www.mcdonaldobservatory.org

  - title: Black Hole Chokes on a Swallowed Star
    img: img/star-disruption-combo.jpg
    attrib: McDonald Observatory &mdash; www.mcdonaldobservatory.org

  - title: An artist''s concept of the Giant Magellan Telescope.
    img: img/gmt1.jpg
    attrib: Todd Mason/GMT Consortium/Carnegie Observatories

  - title: McDonald Observatory Domes
    img: img/domes.jpg
    attrib: McDonald Observatory &mdash; www.mcdonaldobservatory.org

  - title: The Hobby-Eberle Telescope
    img: img/het.jpg
    attrib: McDonald Observatory &mdash; www.mcdonaldobservatory.org
  
  - title: Saturn''s Rings in Ultraviolet Light
    img: img/hs-2003-23-b-full_jpg.jpg
    attrib: HubbleSite &mdash; www.hubblesite.org

  - title: Jupiter
    img: img/hs-2007-25-d-large_web.jpg
    attrib: HubbleSite &mdash; www.hubblesite.org &mdash; NASA, ESA, and A. Simon-Miller (NASA Goddard Space Flight Center)

  - title: Uranus
    img: img/hs-1998-35-a-full_jpg.jpg
    attrib: HubbleSite &mdash; www.hubblesite.org &mdash; Erich Karkoschka (University of Arizona) and NASA

  - title: Mars
    img: img/hs-2001-24-a-full_jpg.jpg
    attrib: HubbleSite &mdash; www.hubblesite.org &mdash; NASA and The Hubble Heritage Team (STScI/AURA)

  - title: Pluto
    img: img/hs-2010-06-d-full_jpg.jpg
    attrib: HubbleSite &mdash; www.hubblesite.org &mdash;  NASA, ESA, and M. Buie (Southwest Research Institute)

  - title: Uranus
    img: img/hs-1998-35-a-full_jpg-1.jpg
    attrib: HubbleSite &mdash; www.hubblesite.org &mdash; Erich Karkoschka (University of Arizona) and NASA

  - title: Neptune
    img: img/hs-2011-19-a-large_web.jpg
    attrib: HubbleSite &mdash; www.hubblesite.org &mdash; NASA, ESA, and the Hubble Heritage Team (STScI/AURA)
    
  - title: Saturn Aurora
    img: img/hs-2005-06-b-large_web.jpg
    attrib: HubbleSite &mdash; www.hubblesite.org &mdash; NASA, ESA, J. Clarke (Boston University), and Z. Levay (STScI)
    
  - title: The Ring Nebula
    img: img/hs-2013-13-b-large_web.jpg
    attrib: HubbleSite &mdash; www.hubblesite.org &mdash; NASA, ESA, and the Hubble Heritage (STScI/AURA)-ESA/Hubble Collaboration

  - title: Saturn
    img: img/hs-2001-15-c-large_web.jpg
    attrib: HubbleSite &mdash; www.hubblesite.org &mdash; NASA and the Hubble Heritage (STScI/AURA)

  - title: Europa
    img: img/pia19048_732.jpg
    attrib: NASA PhotoJournal &mdash; photojournal.jpl.nasa.gov

  - title: Triton
    img: img/P353171_732.jpg
    attrib: NASA PhotoJournal &mdash; photojournal.jpl.nasa.gov

  - title: "Rosetta's Comet From 177 Miles"
    img: img/comet_on_3_august_2014_732.png
    attrib: NASA PhotoJournal &mdash; photojournal.jpl.nasa.gov
    
  - title: Mercury
    img: img/PIA15160_br.jpg
    attrib: NASA PhotoJournal &mdash; photojournal.jpl.nasa.gov
        
  - title: Comet Hale-Bopp
    img: img/104_hb_mai_732.jpg
    attrib: NASA PhotoJournal &mdash; photojournal.jpl.nasa.gov
    
  - title: Venus
    img: img/Venus_Clouds_br.jpg
    attrib: NSSDC Photo Gallery

  - title: Volcanic Activity on Io
    img: img/Clouds_br.jpg
    attrib: NASA/JPL

  - title: The Crab Nebula
    img: img/crab_vlt_big_732X520.jpg
    attrib: VLT

  
    
